### PR TITLE
Fix highlighting of signed vs unsigned arguments

### LINKED ISSUE #193: ARM: Stack offset immediates not considered equal between add and load instructions when highlighting
Image

Image

Related issue (PPC): #32

### PR DESCRIPTION
**Pull request by LagoLunatic**
Fixes #193. It seems like objdiff already had code in place to consider unsigned and signed arguments to be the same (`loose_eq`) but that was only being used in `impl PartialEq<DiffText<'_>> for HighlightKind` and not in `impl PartialEq<HighlightKind> for HighlightKind`, so I just copy pasted that and now it works.

image

### CODE REVIEW

File: objdiff-core/src/diff/display.rs [hunk 1]
```diff
@@ -77,7 +77,7 @@ impl<'a> DiffTextSegment<'a> {
 const EOL_SEGMENT: DiffTextSegment<'static> =
     DiffTextSegment { text: DiffText::Eol, color: DiffTextColor::Normal, pad_to: 0 };
 
-#[derive(Debug, Default, Clone, PartialEq, Eq)]
+#[derive(Debug, Default, Clone, Eq)]
```
Comment (encounter) [inline objdiff-core/src/diff/display.rs:80]: Let’s remove the Eq derive so we don’t accidentally use it

**Review by encounter — COMMENTED** [review]
Thanks for this!

File: objdiff-core/src/diff/display.rs (hunk 1 above)
Comment (LagoLunatic) [reply objdiff-core/src/diff/display.rs]: Done
